FORMAT: 1A
HOST: http://www.ioweyou.pl/api

# I Owe YOU!
Public API of ***I Owe YOU!*** application.

# Group Entry
Entry related resources of the **Entry API**

The Gist resource has the following attributes:

- id
- name
- description
- value
- lender_id
- accepted_at
- created_at
- updated_at
- debtor_id
- rejected_at
- status
- debtor_first_name
- debtor_last_name
- debtor_username
- lender_first_name
- lender_last_name
- lender_username

## Entries Collection [/entries{?contractor}{?from}{?to}{?limit}{?name}{?offset}{?status}]  
+ Parameters
    + contractor (optional, integer) ... user id
    + from (optional, timestamp) ... date from
    + limit (optional, integer) ... limit of entries to fetch
    + name (optional, string) ... part of the name
    + offset (optional, string) ... offset
    + status (optional, string) ... status of entry
    + to (optional, timestamp) ... date to
    
### Fetch [GET]
+ Request

    + Headers
        
            Authorization: 19f036e9-8ff3-4cff-895c-d763757754d6
            
+ Response 201 (application/json)

        [
            {
                id: 1,
                name: 'sample name',
                description: 'sample description',
                value: '5432.00',
                lender_id: 1,
                accepted_at: Wed Sep 18 2013 20:52:06 GMT+0200 (CEST),
                created_at: Wed Aug 14 2013 20:09:48 GMT+0200 (CEST),
                updated_at: Wed Oct 02 2013 20:26:57 GMT+0200 (CEST),
                debtor_id: 2,
                rejected_at: null,
                status: 0,
                debtor_first_name: 'DebtorFirstName',
                debtor_last_name: 'DebtorLastName',
                debtor_username: 'debtor',
                lender_first_name: 'LenderFirstName',
                lender_last_name: 'LenderLastName',
                lender_username: 'lender'
            }
            {
                id: 2,
                name: 'sample name2',
                description: 'sample description2',
                value: '10.00',
                lender_id: 1,
                accepted_at: Wed Sep 18 2013 00:02:17 GMT+0200 (CEST),
                created_at: Sun Oct 10 2010 10:00:00 GMT+0200 (CEST),
                updated_at: Sun Oct 10 2010 10:00:01 GMT+0200 (CEST),
                debtor_id: 2,
                rejected_at: null,
                status: 0,
                debtor_first_name: 'DebtorFirstName',
                debtor_last_name: 'DebtorLastName',
                debtor_username: 'debtor',
                lender_first_name: 'LenderFirstName',
                lender_last_name: 'LenderLastName',
                lender_username: 'lender'
            }
        ]
     
## Entries Collection [/entries/summary{?contractor}{?from}{?to}{?limit}{?name}{?offset}{?status}]  
+ Parameters
    + contractor (optional, integer) ... user id
    + from (optional, timestamp) ... date from
    + limit (optional, integer) ... limit of entries to fetch
    + name (optional, string) ... part of the name
    + offset (optional, string) ... offset
    + status (optional, string) ... status of entry
    + to (optional, timestamp) ... date to
    
### Summary [GET]
+ Request

    + Headers
        
            Authorization: 19f036e9-8ff3-4cff-895c-d763757754d6
            
+ Response 200 (application/json)

        {
            "summary": 12312, 
        }

## Entries Collection [/entries/count{?contractor}{?from}{?to}{?limit}{?name}{?offset}{?status}]  
+ Parameters
    + contractor (optional, integer) ... user id
    + from (optional, timestamp) ... date from
    + limit (optional, integer) ... limit of entries to fetch
    + name (optional, string) ... part of the name
    + offset (optional, string) ... offset
    + status (optional, string) ... status of entry
    + to (optional, timestamp) ... date to
    
### Count [GET]
+ Request

    + Headers
        
            Authorization: 19f036e9-8ff3-4cff-895c-d763757754d6
            
+ Response 200 (application/json)

        {
            "aggregate": 12312, 
        }
        
## Entry [/entries]      
### Create [POST]
+ Request

    + Headers
        
            Authorization: 19f036e9-8ff3-4cff-895c-d763757754d6
    
    + Body
    
            {
                "name": 'sample name', 
                "description": 'sample description',
                "value": '5432.00', 
                "includeMe" 1,
                "contractors": [1, 2, 4]
            }
            
+ Response 201 (application/json)

        {
            "isCreated": 1
        }
 
     
## Entry [/entry/{id}]

+ Parameters

    + id (integer) ... ID of the Entry.
    
### Fetch [GET]
+ Request

    + Headers
        
            Authorization: 19f036e9-8ff3-4cff-895c-d763757754d6
            
+ Response 200 (application/json)

        {
            "id": 1, 
            "name": 'sample name', 
            "description": 'sample description',
            "value": '5432.00', 
            "lender_id": 1, 
            "accepted_at": Wed Sep 18 2013 20:52:06 GMT+0200 (CEST),
            "created_at": Wed Aug 14 2013 20:09:48 GMT+0200 (CEST),
            "updated_at": Wed Oct 02 2013 20:26:57 GMT+0200 (CEST),
            "debtor_id": 2,
            "rejected_at": null,
            "status": 0, 
            "debtor_first_name": 'DebtorFirstName',
            "debtor_last_name": 'DebtorLastName',
            "debtor_username": 'debtor',
            "lender_first_name": 'LenderFirstName',
            "lender_last_name": 'LenderLastName',
            "lender_username": 'lender'
        }

### Modify [PUT]
+ Request (application/json)

    + Headers
        
            Authorization: 19f036e9-8ff3-4cff-895c-d763757754d6
            
    + Body
    
            { 
                "description": "Lorem ipsum...",
                "name": "Lorem ipsum...",
                "value": "1234.56"
            }
        
            
+ Response 200 (application/json)

        {
            "isModified": 1
        }
        
        
### Delete [DELETE]
+ Request

    + Headers
        
            Authorization: 19f036e9-8ff3-4cff-895c-d763757754d6
        
            
+ Response 200 (application/json)

        {
          "isModified": 1
        }
      
      
## Entry [/entry/accept/{id}]
### Accept [POST]
+ Request

    + Headers
        
            Authorization: 19f036e9-8ff3-4cff-895c-d763757754d6
        
            
+ Response 200 (application/json)

        {
          "isModified": 1
        }

## Entry [/entry/reject/{id}]
### Reject [POST]
+ Request

    + Headers
        
            Authorization: 19f036e9-8ff3-4cff-895c-d763757754d6
        
            
+ Response 200 (application/json)

        {
          "isModified": 1
        }